import { Policy } from "../types/global";

export const Policies: Policy[] = [
  {
    id: 1,
    name: "Secure Future Term Life",
    type: "Term Life",
    premium: 5000,
    coverage: 1000000,
  },
  {
    id: 2,
    name: "Health Shield Plan",
    type: "Health",
    premium: 3000,
    coverage: 500000,
  },
  {
    id: 3,
    name: "Car Protect Plan",
    type: "Vehicle",
    premium: 2000,
    coverage: 300000,
  },
  {
    id: 4,
    name: "Family Protection Term Life",
    type: "Term Life",
    premium: 5500,
    coverage: 1200000,
  },
  {
    id: 5,
    name: "Comprehensive Health Plan",
    type: "Health",
    premium: 3500,
    coverage: 600000,
  },
  {
    id: 6,
    name: "Motorcycle Coverage Plan",
    type: "Vehicle",
    premium: 2500,
    coverage: 400000,
  },
  {
    id: 7,
    name: "Secure Future Term Life Plus",
    type: "Term Life",
    premium: 6000,
    coverage: 1500000,
  },
  {
    id: 8,
    name: "Essential Health Plan",
    type: "Health",
    premium: 2800,
    coverage: 450000,
  },
  {
    id: 9,
    name: "Classic Car Insurance",
    type: "Vehicle",
    premium: 2200,
    coverage: 350000,
  },
  {
    id: 10,
    name: "Lifetime Term Life",
    type: "Term Life",
    premium: 7000,
    coverage: 2000000,
  },
  {
    id: 11,
    name: "Family Health Plan",
    type: "Health",
    premium: 4000,
    coverage: 700000,
  },
  {
    id: 12,
    name: "SUV Coverage Plan",
    type: "Vehicle",
    premium: 2400,
    coverage: 320000,
  },
  {
    id: 13,
    name: "Term Life for Seniors",
    type: "Term Life",
    premium: 8000,
    coverage: 1800000,
  },
  {
    id: 14,
    name: "Student Health Insurance",
    type: "Health",
    premium: 1500,
    coverage: 300000,
  },
  {
    id: 15,
    name: "Electric Vehicle Insurance",
    type: "Vehicle",
    premium: 2600,
    coverage: 370000,
  },
  {
    id: 16,
    name: "Short-Term Life Insurance",
    type: "Term Life",
    premium: 4500,
    coverage: 900000,
  },
  {
    id: 17,
    name: "Critical Illness Health Plan",
    type: "Health",
    premium: 3200,
    coverage: 550000,
  },
  {
    id: 18,
    name: "Van Insurance Plan",
    type: "Vehicle",
    premium: 2300,
    coverage: 310000,
  },
  {
    id: 19,
    name: "Whole Life Insurance",
    type: "Term Life",
    premium: 9000,
    coverage: 2500000,
  },
  {
    id: 20,
    name: "Family Health Coverage",
    type: "Health",
    premium: 5000,
    coverage: 800000,
  },
  {
    id: 21,
    name: "Luxury Car Insurance",
    type: "Vehicle",
    premium: 3000,
    coverage: 500000,
  },
  {
    id: 22,
    name: "Term Life for Parents",
    type: "Term Life",
    premium: 6500,
    coverage: 1300000,
  },
  {
    id: 23,
    name: "Preventive Health Plan",
    type: "Health",
    premium: 3700,
    coverage: 650000,
  },
  {
    id: 24,
    name: "Pickup Truck Insurance",
    type: "Vehicle",
    premium: 2100,
    coverage: 340000,
  },
  {
    id: 25,
    name: "Guaranteed Issue Term Life",
    type: "Term Life",
    premium: 7500,
    coverage: 1600000,
  },
];
